// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: device.proto

package dev.duti.ganyu.device;

public interface ContactOrBuilder extends
    // @@protoc_insertion_point(interface_extends:device.Contact)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string phone_number = 1;</code>
   * @return The phoneNumber.
   */
  java.lang.String getPhoneNumber();
  /**
   * <code>string phone_number = 1;</code>
   * @return The bytes for phoneNumber.
   */
  com.google.protobuf.ByteString
      getPhoneNumberBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
