// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: device.proto

package dev.duti.ganyu.device;

public interface ContactsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:device.Contacts)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .device.Contact contacts = 1;</code>
   */
  java.util.List<dev.duti.ganyu.device.Contact> 
      getContactsList();
  /**
   * <code>repeated .device.Contact contacts = 1;</code>
   */
  dev.duti.ganyu.device.Contact getContacts(int index);
  /**
   * <code>repeated .device.Contact contacts = 1;</code>
   */
  int getContactsCount();
  /**
   * <code>repeated .device.Contact contacts = 1;</code>
   */
  java.util.List<? extends dev.duti.ganyu.device.ContactOrBuilder> 
      getContactsOrBuilderList();
  /**
   * <code>repeated .device.Contact contacts = 1;</code>
   */
  dev.duti.ganyu.device.ContactOrBuilder getContactsOrBuilder(
      int index);
}
