// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: device.proto

package dev.duti.ganyu.device;

/**
 * Protobuf type {@code device.Contacts}
 */
public final class Contacts extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:device.Contacts)
    ContactsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Contacts.newBuilder() to construct.
  private Contacts(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Contacts() {
    contacts_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Contacts();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dev.duti.ganyu.device.DeviceOuterClass.internal_static_device_Contacts_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dev.duti.ganyu.device.DeviceOuterClass.internal_static_device_Contacts_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dev.duti.ganyu.device.Contacts.class, dev.duti.ganyu.device.Contacts.Builder.class);
  }

  public static final int CONTACTS_FIELD_NUMBER = 1;
  private java.util.List<dev.duti.ganyu.device.Contact> contacts_;
  /**
   * <code>repeated .device.Contact contacts = 1;</code>
   */
  @java.lang.Override
  public java.util.List<dev.duti.ganyu.device.Contact> getContactsList() {
    return contacts_;
  }
  /**
   * <code>repeated .device.Contact contacts = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends dev.duti.ganyu.device.ContactOrBuilder> 
      getContactsOrBuilderList() {
    return contacts_;
  }
  /**
   * <code>repeated .device.Contact contacts = 1;</code>
   */
  @java.lang.Override
  public int getContactsCount() {
    return contacts_.size();
  }
  /**
   * <code>repeated .device.Contact contacts = 1;</code>
   */
  @java.lang.Override
  public dev.duti.ganyu.device.Contact getContacts(int index) {
    return contacts_.get(index);
  }
  /**
   * <code>repeated .device.Contact contacts = 1;</code>
   */
  @java.lang.Override
  public dev.duti.ganyu.device.ContactOrBuilder getContactsOrBuilder(
      int index) {
    return contacts_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < contacts_.size(); i++) {
      output.writeMessage(1, contacts_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < contacts_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, contacts_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dev.duti.ganyu.device.Contacts)) {
      return super.equals(obj);
    }
    dev.duti.ganyu.device.Contacts other = (dev.duti.ganyu.device.Contacts) obj;

    if (!getContactsList()
        .equals(other.getContactsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getContactsCount() > 0) {
      hash = (37 * hash) + CONTACTS_FIELD_NUMBER;
      hash = (53 * hash) + getContactsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dev.duti.ganyu.device.Contacts parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.duti.ganyu.device.Contacts parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.duti.ganyu.device.Contacts parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.duti.ganyu.device.Contacts parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.duti.ganyu.device.Contacts parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.duti.ganyu.device.Contacts parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.duti.ganyu.device.Contacts parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dev.duti.ganyu.device.Contacts parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static dev.duti.ganyu.device.Contacts parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static dev.duti.ganyu.device.Contacts parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dev.duti.ganyu.device.Contacts parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dev.duti.ganyu.device.Contacts parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dev.duti.ganyu.device.Contacts prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code device.Contacts}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:device.Contacts)
      dev.duti.ganyu.device.ContactsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.duti.ganyu.device.DeviceOuterClass.internal_static_device_Contacts_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.duti.ganyu.device.DeviceOuterClass.internal_static_device_Contacts_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.duti.ganyu.device.Contacts.class, dev.duti.ganyu.device.Contacts.Builder.class);
    }

    // Construct using dev.duti.ganyu.device.Contacts.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (contactsBuilder_ == null) {
        contacts_ = java.util.Collections.emptyList();
      } else {
        contacts_ = null;
        contactsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dev.duti.ganyu.device.DeviceOuterClass.internal_static_device_Contacts_descriptor;
    }

    @java.lang.Override
    public dev.duti.ganyu.device.Contacts getDefaultInstanceForType() {
      return dev.duti.ganyu.device.Contacts.getDefaultInstance();
    }

    @java.lang.Override
    public dev.duti.ganyu.device.Contacts build() {
      dev.duti.ganyu.device.Contacts result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dev.duti.ganyu.device.Contacts buildPartial() {
      dev.duti.ganyu.device.Contacts result = new dev.duti.ganyu.device.Contacts(this);
      int from_bitField0_ = bitField0_;
      if (contactsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          contacts_ = java.util.Collections.unmodifiableList(contacts_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.contacts_ = contacts_;
      } else {
        result.contacts_ = contactsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dev.duti.ganyu.device.Contacts) {
        return mergeFrom((dev.duti.ganyu.device.Contacts)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dev.duti.ganyu.device.Contacts other) {
      if (other == dev.duti.ganyu.device.Contacts.getDefaultInstance()) return this;
      if (contactsBuilder_ == null) {
        if (!other.contacts_.isEmpty()) {
          if (contacts_.isEmpty()) {
            contacts_ = other.contacts_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureContactsIsMutable();
            contacts_.addAll(other.contacts_);
          }
          onChanged();
        }
      } else {
        if (!other.contacts_.isEmpty()) {
          if (contactsBuilder_.isEmpty()) {
            contactsBuilder_.dispose();
            contactsBuilder_ = null;
            contacts_ = other.contacts_;
            bitField0_ = (bitField0_ & ~0x00000001);
            contactsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getContactsFieldBuilder() : null;
          } else {
            contactsBuilder_.addAllMessages(other.contacts_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              dev.duti.ganyu.device.Contact m =
                  input.readMessage(
                      dev.duti.ganyu.device.Contact.parser(),
                      extensionRegistry);
              if (contactsBuilder_ == null) {
                ensureContactsIsMutable();
                contacts_.add(m);
              } else {
                contactsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<dev.duti.ganyu.device.Contact> contacts_ =
      java.util.Collections.emptyList();
    private void ensureContactsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        contacts_ = new java.util.ArrayList<dev.duti.ganyu.device.Contact>(contacts_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        dev.duti.ganyu.device.Contact, dev.duti.ganyu.device.Contact.Builder, dev.duti.ganyu.device.ContactOrBuilder> contactsBuilder_;

    /**
     * <code>repeated .device.Contact contacts = 1;</code>
     */
    public java.util.List<dev.duti.ganyu.device.Contact> getContactsList() {
      if (contactsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(contacts_);
      } else {
        return contactsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .device.Contact contacts = 1;</code>
     */
    public int getContactsCount() {
      if (contactsBuilder_ == null) {
        return contacts_.size();
      } else {
        return contactsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .device.Contact contacts = 1;</code>
     */
    public dev.duti.ganyu.device.Contact getContacts(int index) {
      if (contactsBuilder_ == null) {
        return contacts_.get(index);
      } else {
        return contactsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .device.Contact contacts = 1;</code>
     */
    public Builder setContacts(
        int index, dev.duti.ganyu.device.Contact value) {
      if (contactsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureContactsIsMutable();
        contacts_.set(index, value);
        onChanged();
      } else {
        contactsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .device.Contact contacts = 1;</code>
     */
    public Builder setContacts(
        int index, dev.duti.ganyu.device.Contact.Builder builderForValue) {
      if (contactsBuilder_ == null) {
        ensureContactsIsMutable();
        contacts_.set(index, builderForValue.build());
        onChanged();
      } else {
        contactsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .device.Contact contacts = 1;</code>
     */
    public Builder addContacts(dev.duti.ganyu.device.Contact value) {
      if (contactsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureContactsIsMutable();
        contacts_.add(value);
        onChanged();
      } else {
        contactsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .device.Contact contacts = 1;</code>
     */
    public Builder addContacts(
        int index, dev.duti.ganyu.device.Contact value) {
      if (contactsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureContactsIsMutable();
        contacts_.add(index, value);
        onChanged();
      } else {
        contactsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .device.Contact contacts = 1;</code>
     */
    public Builder addContacts(
        dev.duti.ganyu.device.Contact.Builder builderForValue) {
      if (contactsBuilder_ == null) {
        ensureContactsIsMutable();
        contacts_.add(builderForValue.build());
        onChanged();
      } else {
        contactsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .device.Contact contacts = 1;</code>
     */
    public Builder addContacts(
        int index, dev.duti.ganyu.device.Contact.Builder builderForValue) {
      if (contactsBuilder_ == null) {
        ensureContactsIsMutable();
        contacts_.add(index, builderForValue.build());
        onChanged();
      } else {
        contactsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .device.Contact contacts = 1;</code>
     */
    public Builder addAllContacts(
        java.lang.Iterable<? extends dev.duti.ganyu.device.Contact> values) {
      if (contactsBuilder_ == null) {
        ensureContactsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, contacts_);
        onChanged();
      } else {
        contactsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .device.Contact contacts = 1;</code>
     */
    public Builder clearContacts() {
      if (contactsBuilder_ == null) {
        contacts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        contactsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .device.Contact contacts = 1;</code>
     */
    public Builder removeContacts(int index) {
      if (contactsBuilder_ == null) {
        ensureContactsIsMutable();
        contacts_.remove(index);
        onChanged();
      } else {
        contactsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .device.Contact contacts = 1;</code>
     */
    public dev.duti.ganyu.device.Contact.Builder getContactsBuilder(
        int index) {
      return getContactsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .device.Contact contacts = 1;</code>
     */
    public dev.duti.ganyu.device.ContactOrBuilder getContactsOrBuilder(
        int index) {
      if (contactsBuilder_ == null) {
        return contacts_.get(index);  } else {
        return contactsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .device.Contact contacts = 1;</code>
     */
    public java.util.List<? extends dev.duti.ganyu.device.ContactOrBuilder> 
         getContactsOrBuilderList() {
      if (contactsBuilder_ != null) {
        return contactsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(contacts_);
      }
    }
    /**
     * <code>repeated .device.Contact contacts = 1;</code>
     */
    public dev.duti.ganyu.device.Contact.Builder addContactsBuilder() {
      return getContactsFieldBuilder().addBuilder(
          dev.duti.ganyu.device.Contact.getDefaultInstance());
    }
    /**
     * <code>repeated .device.Contact contacts = 1;</code>
     */
    public dev.duti.ganyu.device.Contact.Builder addContactsBuilder(
        int index) {
      return getContactsFieldBuilder().addBuilder(
          index, dev.duti.ganyu.device.Contact.getDefaultInstance());
    }
    /**
     * <code>repeated .device.Contact contacts = 1;</code>
     */
    public java.util.List<dev.duti.ganyu.device.Contact.Builder> 
         getContactsBuilderList() {
      return getContactsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        dev.duti.ganyu.device.Contact, dev.duti.ganyu.device.Contact.Builder, dev.duti.ganyu.device.ContactOrBuilder> 
        getContactsFieldBuilder() {
      if (contactsBuilder_ == null) {
        contactsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            dev.duti.ganyu.device.Contact, dev.duti.ganyu.device.Contact.Builder, dev.duti.ganyu.device.ContactOrBuilder>(
                contacts_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        contacts_ = null;
      }
      return contactsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:device.Contacts)
  }

  // @@protoc_insertion_point(class_scope:device.Contacts)
  private static final dev.duti.ganyu.device.Contacts DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dev.duti.ganyu.device.Contacts();
  }

  public static dev.duti.ganyu.device.Contacts getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Contacts>
      PARSER = new com.google.protobuf.AbstractParser<Contacts>() {
    @java.lang.Override
    public Contacts parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Contacts> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Contacts> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dev.duti.ganyu.device.Contacts getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

