// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: device.proto

package dev.duti.ganyu.device;

public final class DeviceOuterClass {
  private DeviceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_device_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_device_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_device_Contact_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_device_Contact_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_device_Messages_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_device_Messages_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_device_Contacts_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_device_Contacts_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014device.proto\022\006device\"0\n\007Message\022\024\n\014pho" +
      "ne_number\030\001 \001(\t\022\017\n\007content\030\002 \001(\t\"-\n\007Cont" +
      "act\022\024\n\014phone_number\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\"" +
      "-\n\010Messages\022!\n\010messages\030\001 \003(\0132\017.device.M" +
      "essage\"-\n\010Contacts\022!\n\010contacts\030\001 \003(\0132\017.d" +
      "evice.ContactB9\n\025dev.duti.ganyu.deviceB\020" +
      "DeviceOuterClassP\001Z\014proto/deviceb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_device_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_device_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_device_Message_descriptor,
        new java.lang.String[] { "PhoneNumber", "Content", });
    internal_static_device_Contact_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_device_Contact_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_device_Contact_descriptor,
        new java.lang.String[] { "PhoneNumber", "Name", });
    internal_static_device_Messages_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_device_Messages_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_device_Messages_descriptor,
        new java.lang.String[] { "Messages", });
    internal_static_device_Contacts_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_device_Contacts_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_device_Contacts_descriptor,
        new java.lang.String[] { "Contacts", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
