// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: device.proto

package dev.duti.ganyu.device;

public interface MessagesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:device.Messages)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .device.Message messages = 1;</code>
   */
  java.util.List<dev.duti.ganyu.device.Message> 
      getMessagesList();
  /**
   * <code>repeated .device.Message messages = 1;</code>
   */
  dev.duti.ganyu.device.Message getMessages(int index);
  /**
   * <code>repeated .device.Message messages = 1;</code>
   */
  int getMessagesCount();
  /**
   * <code>repeated .device.Message messages = 1;</code>
   */
  java.util.List<? extends dev.duti.ganyu.device.MessageOrBuilder> 
      getMessagesOrBuilderList();
  /**
   * <code>repeated .device.Message messages = 1;</code>
   */
  dev.duti.ganyu.device.MessageOrBuilder getMessagesOrBuilder(
      int index);
}
