//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: device.proto

package dev.duti.ganyu.device;

@kotlin.jvm.JvmSynthetic
public inline fun message(block: dev.duti.ganyu.device.MessageKt.Dsl.() -> kotlin.Unit): dev.duti.ganyu.device.Message =
  dev.duti.ganyu.device.MessageKt.Dsl._create(dev.duti.ganyu.device.Message.newBuilder()).apply { block() }._build()
public object MessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: dev.duti.ganyu.device.Message.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: dev.duti.ganyu.device.Message.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): dev.duti.ganyu.device.Message = _builder.build()

    /**
     * <code>string phone_number = 1;</code>
     */
    public var phoneNumber: kotlin.String
      @JvmName("getPhoneNumber")
      get() = _builder.getPhoneNumber()
      @JvmName("setPhoneNumber")
      set(value) {
        _builder.setPhoneNumber(value)
      }
    /**
     * <code>string phone_number = 1;</code>
     */
    public fun clearPhoneNumber() {
      _builder.clearPhoneNumber()
    }

    /**
     * <code>string content = 2;</code>
     */
    public var content: kotlin.String
      @JvmName("getContent")
      get() = _builder.getContent()
      @JvmName("setContent")
      set(value) {
        _builder.setContent(value)
      }
    /**
     * <code>string content = 2;</code>
     */
    public fun clearContent() {
      _builder.clearContent()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun dev.duti.ganyu.device.Message.copy(block: dev.duti.ganyu.device.MessageKt.Dsl.() -> kotlin.Unit): dev.duti.ganyu.device.Message =
  dev.duti.ganyu.device.MessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()
