// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: device.proto

package dev.duti.ganyu.device;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:device.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string phone_number = 1;</code>
   * @return The phoneNumber.
   */
  java.lang.String getPhoneNumber();
  /**
   * <code>string phone_number = 1;</code>
   * @return The bytes for phoneNumber.
   */
  com.google.protobuf.ByteString
      getPhoneNumberBytes();

  /**
   * <code>string content = 2;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 2;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
