//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: device.proto

package dev.duti.ganyu.device;

@kotlin.jvm.JvmSynthetic
public inline fun messages(block: dev.duti.ganyu.device.MessagesKt.Dsl.() -> kotlin.Unit): dev.duti.ganyu.device.Messages =
  dev.duti.ganyu.device.MessagesKt.Dsl._create(dev.duti.ganyu.device.Messages.newBuilder()).apply { block() }._build()
public object MessagesKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: dev.duti.ganyu.device.Messages.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: dev.duti.ganyu.device.Messages.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): dev.duti.ganyu.device.Messages = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class MessagesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .device.Message messages = 1;</code>
     */
     public val messages: com.google.protobuf.kotlin.DslList<dev.duti.ganyu.device.Message, MessagesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getMessagesList()
      )
    /**
     * <code>repeated .device.Message messages = 1;</code>
     * @param value The messages to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addMessages")
    public fun com.google.protobuf.kotlin.DslList<dev.duti.ganyu.device.Message, MessagesProxy>.add(value: dev.duti.ganyu.device.Message) {
      _builder.addMessages(value)
    }/**
     * <code>repeated .device.Message messages = 1;</code>
     * @param value The messages to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignMessages")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<dev.duti.ganyu.device.Message, MessagesProxy>.plusAssign(value: dev.duti.ganyu.device.Message) {
      add(value)
    }/**
     * <code>repeated .device.Message messages = 1;</code>
     * @param values The messages to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllMessages")
    public fun com.google.protobuf.kotlin.DslList<dev.duti.ganyu.device.Message, MessagesProxy>.addAll(values: kotlin.collections.Iterable<dev.duti.ganyu.device.Message>) {
      _builder.addAllMessages(values)
    }/**
     * <code>repeated .device.Message messages = 1;</code>
     * @param values The messages to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllMessages")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<dev.duti.ganyu.device.Message, MessagesProxy>.plusAssign(values: kotlin.collections.Iterable<dev.duti.ganyu.device.Message>) {
      addAll(values)
    }/**
     * <code>repeated .device.Message messages = 1;</code>
     * @param index The index to set the value at.
     * @param value The messages to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setMessages")
    public operator fun com.google.protobuf.kotlin.DslList<dev.duti.ganyu.device.Message, MessagesProxy>.set(index: kotlin.Int, value: dev.duti.ganyu.device.Message) {
      _builder.setMessages(index, value)
    }/**
     * <code>repeated .device.Message messages = 1;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearMessages")
    public fun com.google.protobuf.kotlin.DslList<dev.duti.ganyu.device.Message, MessagesProxy>.clear() {
      _builder.clearMessages()
    }}
}
@kotlin.jvm.JvmSynthetic
public inline fun dev.duti.ganyu.device.Messages.copy(block: dev.duti.ganyu.device.MessagesKt.Dsl.() -> kotlin.Unit): dev.duti.ganyu.device.Messages =
  dev.duti.ganyu.device.MessagesKt.Dsl._create(this.toBuilder()).apply { block() }._build()
